import { Dimensions, StyleSheet } from "react-native";
import { Colors } from "react-native/Libraries/NewAppScreen";
const SCREEN_HEIGHT = Dimensions.get('window').height;

export const styles = StyleSheet.create({
    backgroundImage: {
      resizeMode: 'cover',
      flex: 1,
      width: '100%',
      height: '100%',
      backgroundColor: '#24203F',
    },
    noText:{
      top: SCREEN_HEIGHT / 3,
      borderRadius: 20,
      backgroundColor: 'rgba(30, 30, 30, 0.5)',
      padding: 30,
      alignItems: 'center',
    },
    banner: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.7)',
      zIndex: 9999,
      justifyContent: 'center',
      alignItems: 'center',
    },
    container: {
      flex: 1,
    },
    header: {
      paddingTop: 70,
      paddingHorizontal: 16,
      paddingBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      // backgroundColor,
      borderBottomWidth: 1,
      borderBottomColor: Colors.light,
    },
    headerText: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    switchThemeButton: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    switchThemeText: {
      fontSize: 14,
      fontWeight: '600',
    },
    messagesContainer: {
      flex: 1,
    },
    messagesContent: {
      padding: 16,
    },
    messageBubble: {
      maxWidth: '80%',
      padding: 12,
      marginBottom: 8,
    },
    userBubble: {
      borderTopLeftRadius: 20,
      borderBottomRightRadius: 20,
      borderBottomLeftRadius: 20,
      backgroundColor: 'rgba(34,40,49,0.7)',
      alignSelf: 'flex-end',
    },
    botBubble: {
        borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
      borderBottomLeftRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.7)',
      alignSelf: 'flex-start',
    },
    messageText: {
      fontSize: 16,
    },
    timestamp: {
      fontSize: 12,
      color: Colors.white,
      marginTop: 4,
     textAlign: 'right'
    },
    inputContainer: {
      // bottom: 15,
      // flexDirection: 'row',
      // padding: 16,
    },
    input: {
      flex: 1,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginRight: 8,
    },
    sendButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      justifyContent: 'center',
    },
    sendButtonText: {
      fontWeight: 'bold',
    },
    typingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
    },
    typingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.dark,
      marginHorizontal: 2,
    },
    typingBubble: {
      backgroundColor: Colors.light,
      padding: 8,
      borderRadius: 20,
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    actionIndicator: {
      backgroundColor: '#1F1F1F',
      padding: 8,
      position: 'absolute',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.1)',
      bottom: 75,
      width: '100%',
      zIndex: 999,
    },
    actionIndicatorContent: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: '#2C2C2C',
      borderRadius: 12,
      marginHorizontal: 4,
    },
    actionLabel: {
      fontSize: 14,
      color: '#8E44AD',
      fontWeight: '600',
      marginRight: 8,
    },
    actionText: {
      flex: 1,
      fontSize: 14,
      color: '#FFFFFF',
      opacity: 0.9,
    },
    closeActionButton: {
      borderRadius: 50,
      height: 30,
      width: 30,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    closeActionText: {
      fontSize: 18,
      color: '#FFFFFF',
      opacity: 0.8,
    },
    replyPreview: {
      borderLeftWidth: 3,
      borderLeftColor: Colors.primary,
      paddingLeft: 8,
      marginBottom: 8,
    },
    replyPreviewText: {
      fontSize: 14,
      color: Colors.dark,
      opacity: 0.7,
    },
    reactionPickerOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    reactionPicker: {
      flexDirection: 'row',
      backgroundColor: Colors.white,
      borderRadius: 20,
      padding: 12,
      shadowColor: Colors.black,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    reactionButton: {
      padding: 8,
      marginHorizontal: 4,
    },
    reactionEmoji: {
      fontSize: 24,
    },
    reactionCount: {
      fontSize: 12,
      color: Colors.dark,
      textAlign: 'center',
    },
    reactionsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      top:5
    },
    reactionBubble: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.light,
      borderRadius: 12,
      paddingHorizontal: 6,
      paddingVertical: 2,
      marginLeft: 4,
      marginTop: 4,
    },
    attachmentButton: {
      padding: 8,
      marginRight: 8,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    attachmentModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'flex-end',
    },
    attachmentModalSheet: {
      backgroundColor: '#fff',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      alignItems: 'center',
    },
    attachmentModalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 16,
    },
    attachmentOptionsRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '100%',
    },
    attachmentOption: {
      alignItems: 'center',
      marginHorizontal: 24,
    },
    attachmentOptionIcon: {
      fontSize: 36,
      marginBottom: 8,
    },
    attachmentOptionLabel: {
      fontSize: 14,
      color: '#333',
    },
    attachmentImageContainer: {
      marginBottom: 8,
      borderRadius: 12,
      overflow: 'hidden',
    },
    attachmentImage: {
      width: 180,
      height: 120,
      borderRadius: 12,
      backgroundColor: '#eee',
    },
    audioContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      borderRadius: 12,
      padding: 8,
      overflow: 'hidden',
    },
    audioContainerPlaying: {
      position: 'relative',
    },
    audioBackgroundGif: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      opacity: 0.2,
    },
    audioPlayButton: {
      marginRight: 8,
      padding: 8,
      borderRadius: 16,
      backgroundColor: '#fff',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    audioPlayIcon: {
      fontSize: 22,
    },
    audioProgressBarBg: {
      flex: 1,
      height: 4,
      backgroundColor: '#ccc',
      borderRadius: 2,
      marginHorizontal: 8,
      overflow: 'hidden',
    },
    audioProgressBarFg: {
      height: 4,
      backgroundColor: '#007AFF',
      borderRadius: 2,
    },
    audioTime: {
      fontSize: 12,
      color: '#fff',
      marginLeft: 8,
      minWidth: 40,
      textAlign: 'right',
    },
    waReactionBar: {
      position: 'absolute',
      width: 320,
      height: 56,
      backgroundColor: '#2C2C2C',
      borderRadius: 32,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 2},
      elevation: 5,
      zIndex: 100,
    },
    waReactionBarContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      width: '100%',
      height: 40,
      paddingHorizontal: 10,
    },
    waReactionEmoji: {
      fontSize: 24,
      textAlign: 'center',
    },
    waReactionBarTriangle: {
      position: 'absolute',
      left: '50%',
      bottom: -10,
      marginLeft: -10,
      width: 0,
      height: 0,
      backgroundColor: 'transparent',
      borderStyle: 'solid',
      borderLeftWidth: 10,
      borderRightWidth: 10,
      borderTopWidth: 10,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderTopColor: '#2C2C2C',
    },
    emojiPickerContainer: {
      height: 250,
      backgroundColor: '#1F1F1F',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.1)',
    },
    bottomRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      marginTop: 4,
      gap: 4,
    },
    recordingOverlay: {
      position: 'absolute',
      bottom: 70,
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      // backgroundColor: 'rgba(0,0,0,0.8)',
      paddingVertical: 20,
    },
    recordingGradient: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordingPulse: {
      top:10,
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: 'rgba(255,0,0,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordingDot: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'red',
    },
    recordingTime: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginTop: 12,
      paddingBottom:10,
    },
    recordingHint: {
      color: 'rgba(255,255,255,0.7)',
      fontSize: 14,
      marginTop: 8,
    },
  });